apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-run-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: run-qsdev
    profiles: [dev]
  - targetId: run-qsqa
    profiles: [qa]
  - targetId: run-qsprod
    profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsdev
description: Cloud Run development service
run:
  location: projects/leroy-sandbox/locations/europe-west1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsqa
description: Cloud Run qa service
run:
  location: projects/leroy-sandbox/locations/europe-west1

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-qsprod
description: Cloud Run production service
requireApproval: true
run:
  location: projects/leroy-sandbox/locations/europe-west1

