apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-run-service-qa
spec:
  template:
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/leroy-sandbox/gcp-cloud-deploy/go-app:latest