apiVersion: skaffold/v4beta7
kind: Config
metadata: 
  name: deploy-run-quickstart
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-service-dev.yaml
- name: qa
  manifests:
    rawYaml:
    - run-service-qa.yaml
- name: prod
  manifests:
    rawYaml:
    - run-service-prod.yaml
deploy:
  cloudrun: {}